### ISSUE TITLE
Preparation for mirroring repo

### ISSUE THREAD

**Issue by mbtools** [sbcgua/abap-string-map#7]
I'm trying to mirror the repo into my namespace (similar to AJSON in AG). There are a few things that abaplint can't do automatically:

- Adjusting variable names (`lx` to `lx_error`)

![image](https://user-images.githubusercontent.com/59966492/122785054-53181c00-d2b3-11eb-8006-6b3a48a155b5.png)

- Reorder definitions with BEGIN/END to top (https://github.com/abaplint/abaplint/issues/1505)

![image](https://user-images.githubusercontent.com/59966492/122785145-67f4af80-d2b3-11eb-8bd2-6412ba9647f9.png)

- Method chaining (702)

![image](https://user-images.githubusercontent.com/59966492/122785764-f0735000-d2b3-11eb-8cd5-46ef92a1b42b.png)

Do you mind if I make these adjustment in a PR?

**Comment by sbcgua** [comment]
Sure, feel free to PR.

A bit tentative about `lx` - I do like this style - but let's do it too
